name: PvPArenas
main: me.externo6.pvparenas.PvParenas
authers: externo6
version: 2.7
description: >
             Developed for Banxsi.com by externo6. Removes Potion Effects in PVP arenas, and manages kits.
