name: PvPArenas
main: me.externo6.pvparenas.pvparenas
authers: externo6
version: 2.0
description: >
             Developed for Banxsi.com by externo6. Removes Potion Effects in PVP arenas, and manages kits.
